import { useEffect, useRef } from "react";
import { createPortal } from "react-dom";

function Output({ files = [], onClose }) {
    const iframeRef = useRef(null);

        useEffect(() => {
                if (!iframeRef.current) return;

                        const htmlFile = files.find(file =>
                                    file.name.toLowerCase().endsWith(".html")
                                            );

                                                    const cssFile = files.find(file =>
                                                                file.name.toLowerCase().endsWith(".css")
                                                                        );

                                                                                const jsFile = files.find(file =>
                                                                                            file.name.toLowerCase().endsWith(".js")
                                                                                                    );

                                                                                                            const html = htmlFile?.code || "";
                                                                                                                    const css = cssFile?.code || "";
                                                                                                                            const js = jsFile?.code || "";

                                                                                                                                    let finalHTML = html;

                                                                                                                                            const cssTag = css
                                                                                                                                                        ? `<style>${css}</style>`
                                                                                                                                                                    : "";

                                                                                                                                                                            const jsTag = js
                                                                                                                                                                                        ? `<script>${js}<\/script>`
                                                                                                                                                                                                    : "";

                                                                                                                                                                                                            if (finalHTML.includes("</head>")) {
                                                                                                                                                                                                                        finalHTML = finalHTML.replace(
                                                                                                                                                                                                                                        "</head>",
                                                                                                                                                                                                                                                        `${cssTag}</head>`
                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                        finalHTML = `${cssTag}${finalHTML}`;
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                        if (finalHTML.includes("</body>")) {
                                                                                                                                                                                                                                                                                                                    finalHTML = finalHTML.replace(
                                                                                                                                                                                                                                                                                                                                    "</body>",
                                                                                                                                                                                                                                                                                                                                                    `${jsTag}</body>`
                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                    finalHTML += jsTag;
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    iframeRef.current.srcdoc = finalHTML;

                                                                                                                                                                                                                                                                                                                                                                                                        }, [files]);

                                                                                                                                                                                                                                                                                                                                                                                                            return createPortal(
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="output-fullscreen">

                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                className="output-close"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ✕
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <iframe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ref={iframeRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="NestCode Preview"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sandbox="allow-scripts"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.body
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Output;
                                                                
                                                                                
                                                                                

                                                                                                
                                                                                                        
                                                                                        
                                                                                                                                    
                                                                                                                        
                                                                                                                                        

                                                                                                                                                
                                                                                                                                        
                                                                                                                                                                
                                                                                                                                                                

                                                                                                                                                                                        
                                                                                                                                                                                                
                                                                                                                                                                                                        
                                                                                                                                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                
                          
                                    
                                      
                   
              
                                        
                                           
                        

                                              
                                                        
                                                    

                                             

                                                              
                                                      
                                                                        

                                                                                    
                                                                                              
                                                                                                      
                                                                                                                
                                                                                                                  
                                                                                                                  
                                                                                                                        

                                                                                                        
                                                                                                                                          
                                                                                                                                                
                                                                                                                                                      
                                                                                                                                                            
                                                                                                                                                                
                                                                                                                                                                        
                                                                                                                                                                                          
                                                                                                                                                                                                
                                                                                                                                                                                                        

                                                                                                                                                                                                        
                                                                                                                                                                                                                
                                                                                                                                                                                                
                                                                                                                                                                                                      
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                              

                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                    

                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                
                                                                
                                                                                                          
                                                                                                                    
                                                                                                                              
                                                                                                                                
                                                                                                                                                
                                                                                                                                                            
                                                                                                                                                                      
                                                                                                                                                        
                                                                                                                                                                                    
                                                                                                                                                                                

                                                                                                                                                                                                    
                                                                                                                                                                                        
                                                                                                                                                                                                                      
                                                                                                                                                                                                                        

                                                                                                                                                                                                        
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                         